### ISSUE TITLE
The program does not exit the loading screen

### ISSUE THREAD

**Issue by DevWand** [XielQs/httptoolkit-pro-patcher#33] opened 2024-11-11 10:46 UTC
Log:

[+] HTTP Toolkit found at C:\Users\wander\AppData\Local\Programs\httptoolkit
[+] Starting HTTP Toolkit...
[+] Done

[Patcher] Selected temp path: C:\Users\wander\AppData\Local\Temp\httptoolkit-patch
[Patcher] Server listening on port 5067
[Patcher] Request to: /?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1
[Patcher] [ERR] Failed to fetch remote file date AxiosError: Request failed with status code 403
    at settle (C:\Users\wander\AppData\Local\Programs\httptoolkit\resources\app.asar\node_modules\axios\dist\node\axios.cjs:2019:12)
    at IncomingMessage.handleStreamEnd (C:\Users\wander\AppData\Local\Programs\httptoolkit\resources\app.asar\node_modules\axios\dist\node\axios.cjs:3135:11)
    at IncomingMessage.emit (node:events:526:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (C:\Users\wander\AppData\Local\Programs\httptoolkit\resources\app.asar\node_modules\axios\dist\node\axios.cjs:4287:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\wander\AppData\Local\Programs\httptoolkit\resources\app.asar\build\index.js:112:28 {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
      'Content-Type': undefined,
      host: 'app.httptoolkit.tech',
      connection: 'keep-alive',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'pt-BR',
      origin: 'https://app.httptoolkit.tech',
      'sec-fetch-dest': 'document',
      'sec-fetch-mode': 'navigate',
      'sec-fetch-site': 'none',
      'sec-fetch-user': '?1',
      'upgrade-insecure-requests': '1',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.19.1 Chrome/122.0.6261.130 Electron/29.1.5 Safari/537.36',
      referer: 'https://app.httptoolkit.tech/'
    },
    baseURL: 'https://app.httptoolkit.tech',
    method: 'head',
    url: '/?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      error: [Array],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'app.httptoolkit.tech',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'app.httptoolkit.tech',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      timeout: 5000,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 84,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 848,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 86,
        [Symbol(triggerId)]: 0
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'HEAD /?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1 HTTP/1.1\r\n' +
      'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\n' +
      'host: app.httptoolkit.tech\r\n' +
      'connection: keep-alive\r\n' +
      'accept-encoding: gzip, deflate, br\r\n' +
      'accept-language: pt-BR\r\n' +
      'origin: https://app.httptoolkit.tech\r\n' +
      'sec-fetch-dest: document\r\n' +
      'sec-fetch-mode: navigate\r\n' +
      'sec-fetch-site: none\r\n' +
      'sec-fetch-user: ?1\r\n' +
      'upgrade-insecure-requests: 1\r\n' +
      'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.19.1 Chrome/122.0.6261.130 Electron/29.1.5 Safari/537.36\r\n' +
      'referer: https://app.httptoolkit.tech/\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'HEAD',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://app.httptoolkit.tech/?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 20,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: [Function: emitRequestTimeout],
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'app.httptoolkit.tech',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://app.httptoolkit.tech/?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      host: [Array],
      connection: [Array],
      'accept-encoding': [Array],
      'accept-language': [Array],
      origin: [Array],
      'sec-fetch-dest': [Array],
      'sec-fetch-mode': [Array],
      'sec-fetch-site': [Array],
      'sec-fetch-user': [Array],
      'upgrade-insecure-requests': [Array],
      'user-agent': [Array],
      referer: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: Object [AxiosHeaders] {
      date: 'Mon, 11 Nov 2024 10:44:27 GMT',
      'content-type': 'text/html',
      connection: 'keep-alive',
      vary: 'Accept-Encoding',
      server: 'BunnyCDN-FO1-816',
      'cdn-pullzone': '1110200',
      'cdn-uid': '84940c56-1bd0-4fc0-b14b-dda6f6ba9cf3',
      'cdn-requestcountrycode': 'BR',
      'cdn-requestid': '7df2d0a1cef5f9b14bc2fc1a11d37ccf'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      baseURL: 'https://app.httptoolkit.tech',
      method: 'head',
      url: '/?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'HEAD /?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1 HTTP/1.1\r\n' +
        'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\n' +
        'host: app.httptoolkit.tech\r\n' +
        'connection: keep-alive\r\n' +
        'accept-encoding: gzip, deflate, br\r\n' +
        'accept-language: pt-BR\r\n' +
        'origin: https://app.httptoolkit.tech\r\n' +
        'sec-fetch-dest: document\r\n' +
        'sec-fetch-mode: navigate\r\n' +
        'sec-fetch-site: none\r\n' +
        'sec-fetch-user: ?1\r\n' +
        'upgrade-insecure-requests: 1\r\n' +
        'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.19.1 Chrome/122.0.6261.130 Electron/29.1.5 Safari/537.36\r\n' +
        'referer: https://app.httptoolkit.tech/\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'HEAD',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/?authToken=opb2NJVPJDZntn2qMtIzLoRz_G4&desktopVersion=1.19.1',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'app.httptoolkit.tech',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: ''
  },
  status: 403
}
[Patcher] File downloaded and saved: C:\Users\wander\AppData\Local\Temp\httptoolkit-patch\index.html
[Patcher] Request to: /mockttp.js
[Patcher] Request to: /apis.js
[Patcher] Request to: /a219baaae146da8ee8f5.png
[Patcher] Request to: /vendors-node_modules_ajv_dist_ajv_js-node_modules_base64-js_index_js-node_modules_browserify--bb5eaa.js
[Patcher] No internet connection, trying to serve directly from temp path
[Patcher] Serving from temp path: C:\Users\wander\AppData\Local\Temp\httptoolkit-patch\mockttp.js
[Patcher] Request to: /vendors-node_modules_bn_js_lib_bn_js-node_modules_path-browserify_index_js.js
[Patcher] Request to: /vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js
[Patcher] Request to: /main.js
[Patcher] No internet connection, trying to serve directly from temp path
[Patcher] Serving from temp path: C:\Users\wander\AppData\Local\Temp\httptoolkit-patch\a219baaae146da8ee8f5.png
[Patcher] No internet connection, trying to serve directly from temp path
[Patcher] File not found in temp path: C:\Users\wander\AppData\Local\Temp\httptoolkit-patch\vendors-node_modules_ajv_dist_ajv_js-node_modules_base64-js_index_js-node_modules_browserify--bb5eaa.js
[Patcher] No internet connection, trying to serve directly from temp path
[Patcher] File not found in temp path: C:\Users\wander\AppData\Local\Temp\httptoolkit-patch\main.js
[Patcher] No internet connection, trying to serve directly from temp path
[Patcher] File not found in temp path: C:\Users\wander\AppData\Local\Temp\httptoolkit-patch\vendors-node_modules_bn_js_lib_bn_js-node_modules_path-browserify_index_js.js
[Patcher] [ERR] Failed to fetch remote file date AxiosError: Request failed with status code 403
    at settle (C:\Users\wander\AppData\Local\Programs\httptoolkit\resources\app.asar\node_modules\axios\dist\node\axios.cjs:2019:12)
    at IncomingMessage.handleStreamEnd (C:\Users\wander\AppData\Local\Programs\httptoolkit\resources\app.asar\node_modules\axios\dist\node\axios.cjs:3135:11)
    at IncomingMessage.emit (node:events:526:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (C:\Users\wander\AppData\Local\Programs\httptoolkit\resources\app.asar\node_modules\axios\dist\node\axios.cjs:4287:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\wander\AppData\Local\Programs\httptoolkit\resources\app.asar\build\index.js:112:28 {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: '*/*',
      'Content-Type': undefined,
      host: 'app.httptoolkit.tech',
      connection: 'keep-alive',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'pt-BR',
      origin: 'https://app.httptoolkit.tech',
      referer: 'https://app.httptoolkit.tech/',
      'sec-fetch-dest': 'script',
      'sec-fetch-mode': 'no-cors',
      'sec-fetch-site': 'same-origin',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.19.1 Chrome/122.0.6261.130 Electron/29.1.5 Safari/537.36',
      'sec-ch-ua': '"Not(A:Brand";v="24", "Chromium";v="122"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Windows"'
    },
    baseURL: 'https://app.httptoolkit.tech',
    method: 'head',
    url: '/vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      error: [Array],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'app.httptoolkit.tech',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'app.httptoolkit.tech',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      timeout: 5000,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 366,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 1241,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 368,
        [Symbol(triggerId)]: 0
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'HEAD /vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js HTTP/1.1\r\n' +
      'Accept: */*\r\n' +
      'host: app.httptoolkit.tech\r\n' +
      'connection: keep-alive\r\n' +
      'accept-encoding: gzip, deflate, br\r\n' +
      'accept-language: pt-BR\r\n' +
      'origin: https://app.httptoolkit.tech\r\n' +
      'referer: https://app.httptoolkit.tech/\r\n' +
      'sec-fetch-dest: script\r\n' +
      'sec-fetch-mode: no-cors\r\n' +
      'sec-fetch-site: same-origin\r\n' +
      'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.19.1 Chrome/122.0.6261.130 Electron/29.1.5 Safari/537.36\r\n' +
      'sec-ch-ua: "Not(A:Brand";v="24", "Chromium";v="122"\r\n' +
      'sec-ch-ua-mobile: ?0\r\n' +
      'sec-ch-ua-platform: "Windows"\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 2,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'HEAD',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://app.httptoolkit.tech/vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 20,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: [Function: emitRequestTimeout],
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'app.httptoolkit.tech',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://app.httptoolkit.tech/vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      host: [Array],
      connection: [Array],
      'accept-encoding': [Array],
      'accept-language': [Array],
      origin: [Array],
      referer: [Array],
      'sec-fetch-dest': [Array],
      'sec-fetch-mode': [Array],
      'sec-fetch-site': [Array],
      'user-agent': [Array],
      'sec-ch-ua': [Array],
      'sec-ch-ua-mobile': [Array],
      'sec-ch-ua-platform': [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: Object [AxiosHeaders] {
      date: 'Mon, 11 Nov 2024 10:44:27 GMT',
      'content-type': 'text/html',
      connection: 'keep-alive',
      vary: 'Accept-Encoding',
      server: 'BunnyCDN-FO1-816',
      'cdn-pullzone': '1110200',
      'cdn-uid': '84940c56-1bd0-4fc0-b14b-dda6f6ba9cf3',
      'cdn-requestcountrycode': 'BR',
      'cdn-requestid': '7e9b697b8eb98dd868ca1d0cc01b1f91'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      baseURL: 'https://app.httptoolkit.tech',
      method: 'head',
      url: '/vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'HEAD /vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'host: app.httptoolkit.tech\r\n' +
        'connection: keep-alive\r\n' +
        'accept-encoding: gzip, deflate, br\r\n' +
        'accept-language: pt-BR\r\n' +
        'origin: https://app.httptoolkit.tech\r\n' +
        'referer: https://app.httptoolkit.tech/\r\n' +
        'sec-fetch-dest: script\r\n' +
        'sec-fetch-mode: no-cors\r\n' +
        'sec-fetch-site: same-origin\r\n' +
        'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) httptoolkit/1.19.1 Chrome/122.0.6261.130 Electron/29.1.5 Safari/537.36\r\n' +
        'sec-ch-ua: "Not(A:Brand";v="24", "Chromium";v="122"\r\n' +
        'sec-ch-ua-mobile: ?0\r\n' +
        'sec-ch-ua-platform: "Windows"\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'HEAD',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'app.httptoolkit.tech',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: ''
  },
  status: 403
}
Config checked in 12 ms
Certificates setup in 6 ms
Standalone server started in 5 ms
Server started in 17 ms
Total startup took 40 ms
[Patcher] File downloaded and saved: C:\Users\wander\AppData\Local\Temp\httptoolkit-patch\vendors-node_modules_ethersproject_abi_lib_esm_abi-coder_js-node_modules_fortawesome_free-bra-6b000d.js
[Patcher] File not changed, serving from temp path

**Comment by XielQs** [comment] 2024-11-11 11:14
duplicate of #26

**Closed by XielQs** 2024-11-11 11:14 UTC
