### ISSUE TITLE
not working after update

### ISSUE THREAD

**Issue by haemtee** [XielQs/httptoolkit-pro-patcher#12] opened 2024-08-30 13:34 UTC
the tools kit are update and the pro feature now is missing

**Comment by SuperTavor** [comment] 2024-08-30 14:14
Yeah, would be much appreciated if you fixed this

**Comment by CrustyCode** [comment] 2024-08-30 14:28
The issue is that there's a dollar sign added to the accStoreName.

**Comment by CrustyCode** [comment] 2024-08-30 14:40
https://github.com/XielQs/httptoolkit-pro-patcher/pull/13

**Comment by johnblitzseo** [comment] 2024-08-30 14:45
much better if we have option to disable updates. so the patcher will still work

**Comment by XielQs** [comment] 2024-08-30 14:58
thanks @CrustyCode should be fixed ig?

**Comment by CrustyCode** [comment] 2024-08-30 17:26
@XielQs #13 fixes the problem for me. Can anyone confirm? @haemtee @SuperTavor

**Comment by SuperTavor** [comment] 2024-08-30 19:12
I tried your fork, it worked for me this afternoon but now I'm stuck on the HTTP Toolkit loading thing

![image](https://github.com/user-attachments/assets/334e9988-c7c9-44fb-ab40-986667f012d9)

**Comment by XielQs** [comment] 2024-08-30 19:14
can you share a devtools console log?

**Comment by SuperTavor** [comment] 2024-08-30 19:20
Hmm, it suddenly works again. Very strange. 
![image](https://github.com/user-attachments/assets/a0994f87-9b16-4aa4-8c68-b6cb0d988dcd)

**Comment by XielQs** [comment] 2024-08-30 19:25
uh 🤷🏻‍♂️

**Comment by MoriSummerz** [comment] 2024-08-30 22:29
same, just stuck on the loading screen

**Comment by h9nt** [comment] 2024-08-30 22:39
after patching, its not unlock features??

**Comment by h9nt** [comment] 2024-08-30 22:41
all working as usually

**Comment by XielQs** [comment] 2024-08-30 23:13
> same, just stuck on the loading screen
> 
> upd. stucks here ![image](https://private-user-images.githubusercontent.com/48492775/363349063-6ebc7728-7535-4065-907b-879bf6745ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNTk4NzEsIm5iZiI6MTcyNTA1OTU3MSwicGF0aCI6Ii80ODQ5Mjc3NS8zNjMzNDkwNjMtNmViYzc3MjgtNzUzNS00MDY1LTkwN2ItODc5YmY2NzQ1ZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDIzMTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZmQ5YzVjNTllYmQzMjdmNzBlMDU2ZTczYjEyMzdiMDkxZGIzYWE4MjQyNmJjYjNhNzE4ODZlY2I2NzQ1ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AKcR1mV5yJpy0joYckcY_0iUx6TSNjGJ8chfAKMWuEs)

can you leave a screenshot of devtools?

**Comment by haemtee** [comment] 2024-08-31 00:48
> @XielQs #13 fixes the problem for me. Can anyone confirm? @haemtee @SuperTavor

yep its fixed

**Comment by JohnDoe1964** [comment] 2024-08-31 06:17
PS C:\Temp\httptoolkit-pro-patcher> node . patch
node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@electron/asar' imported from C:\Temp\httptoolkit-pro-patcher\index.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.16.0
PS C:\Temp\httptoolkit-pro-patcher>

**Comment by XielQs** [comment] 2024-08-31 10:43
> PS C:\Temp\httptoolkit-pro-patcher> node . patch
> node:internal/modules/esm/resolve:854
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
>         ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@electron/asar' imported from C:\Temp\httptoolkit-pro-patcher\index.js
>     at packageResolve (node:internal/modules/esm/resolve:854:9)
>     at moduleResolve (node:internal/modules/esm/resolve:927:18)
>     at defaultResolve (node:internal/modules/esm/resolve:1169:11)
>     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
>     at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
>     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
>     at link (node:internal/modules/esm/module_job:86:36) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
> 
> Node.js v20.16.0
> PS C:\Temp\httptoolkit-pro-patcher>

you need to install packages with `npm i`

**Closed** 2024-08-31 11:23 UTC
Labels: bug
